services:
  systemmanagement:
    build: .
    restart: always
    environment:
      - API_PORT=${API_PORT}
      - DATA_PATH=${DATA_PATH}
      - LOGGING_PATH=${LOGGING_PATH}
      - CHECKPOINT_PATH=${CHECKPOINT_PATH}
    ports:
      - 8888:8080
    volumes:
      - ./service/model/ckpt:/app/service/model/ckpt
    networks:
      - management_service

networks:
  management_service: